### ISSUE TITLE
Spawn Protection

### ISSUE THREAD

**Issue by LegoFan48737** [XOXOHighRolePlayMCPE/XOHR-Details#5]
So, we need to figure out some way for Spawn Protection. I've tried 2 area plugins, neither works satisfactorily, and we can't use a World Protection plugin for Spawn. 
Current Status: [[JonTron_WHAT_WHATTHEFUCK.mp4]](https://youtu.be/sGtY1aPrOMQ)

**Comment by Switchblade304** [comment]
No idea...

**Comment by LegoFan48737** [comment]
Best bet is probably setting default spawn prots to a measured radius and setting soawn based on said measured radius. Could be an issue depending on length to width ratio for Spawn

**Comment by LegoFan48737** [comment]
Actually, I'm going to run a few more tests with some things, we'll probably end up doing default prots as suggested but this may be a workaround.

**Comment by LegoFan48737** [comment]
Hold the fuckity duck up.
Poggit didn't show me this yesterday.
[iProtector](https://poggit.pmmp.io/p/iProtector/3.1.1)
This solves everything. Hogwarts I'll make a separate plugin that protects hogwarts and adds its warps, and this fixes spawn.
