### ISSUE TITLE
Staff Application Template

### ISSUE THREAD

**Issue by LegoFan48737** [XOXOHighRolePlayMCPE/XOHR-Details#6]
**Staff Application for XOXO High RolePlay MCPE**

*NOTE: All applicants must be 13 years of age or older. If you are younger than 13 years of age, your application will be immediately denied.*

*NOTE: All applicants must have a Discord account, and be able to be reached via their Discord account. If you do not have a Discord account, your application will be immediately denied.*

*Answer each question on the line below the question. Failure to follow this format may result in the denial of you application.*

• Username:

• Discord Username:

• Nickname/What most people call you:

• Age:

• Location (please include Country and Timezone):

• Languages you speak (please mark your primary language as such):

• Prior positions on other servers (Please include what server, and any ranks from Builder/Helper all the way up to Owner/Leader)

• References (if there is someone we can contact for a reference, please list them and their contact info here, however it is not required):

• Why you wish to be a Staff member (must be a Paragraph or more):

• Why we should accept you as a Staff member (must be at least 2 sentences):

• What, if any, are some special qualities about you that you could contribute to the Staff team? (These can include a history of mediation, knowledge of PHP, etc.)

• How active can you be? (Feel free to be specific, although all we need is a generalized number of days per week, and what time of day you'll usually be on):

After filling out all these questions, please submit the form, and await response from a Reviewer.

- What do y'all think about this? Good, or does it need more questions?

**Comment by AbyssNeurax** [comment]
Yeah this is good. I dont see any way to improve lmao.

**Comment by LegoFan48737** [comment]
> Yeah this is good. I dont see any way to improve lmao.

In that case, I'll wait for other feedback, then use Grammarly to check over it, then commit a new template file for it.

**Comment by Switchblade304** [comment]
Looks good

**Comment by LegoFan48737** [comment]
Cara says it looks good, and Becca DMed me as well, that just leaves @ChockyWocky

**Comment by LegoFan48737** [comment]
Ok Chocky says it's good, I'll make the file.
